### ISSUE TITLE
MFC0 and MTC0 instructions not assembled

### ISSUE THREAD

**Issue by abitalive** [Tarek701/CajeASM#3]
In CajeASM.v7.25 MFC0 and MTC0 instructions appear to be skipped by the assembler with no error shown in the logs.

The following code

    .org	0x861C0
    LUI		T1, 0x1234
    MFC0	T2, EPC
    MTC0	T3, COUNT
    LUI		T4, 0x5678

Assembles to

    0x861C0: LUI	T1, 0x1234
    0x861C4: LUI	T4, 0x5678

**Comment by Tarek701** [comment]
Hello, abitalive.
I'm soon working on it.
